name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Check PEP8 compliance
        run: |
          black --check --verbose src tests
      - name: Lint with mypy
        run: |
          mypy src
      - name: Test with pytest
        run: |
          pytest --cov=src tests
